In [50]:
import numpy as np
import matplotlib.pyplot as plt

In [51]:
S4 = np.array([
    [4, 1, 1, 0,1],
    [-1,-3,1,1,0],
    [2,1,5,-1,-1],
    [-1,-1,-1,4,0],
    [0,2,-1,1,4]
])
b4 = np.array([6,6,6,6,6])


S3 = np.array([
    [10, 5, 0, 0],
    [5, 10, -4,0],
    [0,-4, 8, -1],
    [0,0,-1,5]
])
b3 = np.array([6, 25, -11,-11])


S2 = np.array([
    [10, -1, 0],
    [-1, 10, -2],
    [0, -2, 10]
])
b2 = np.array([9,7,6])


S1 = np.array([
    [3, -1, 1],
    [3, 6, 2],
    [3, 3, 7]
])
b1 = np.array([1, 0, 4])

In [52]:
def sor_example(A, b, omega, x0, iterations=2):
    n = len(b) 
    x = x0.copy() 
    
    for iteration in range(iterations):
        for i in range(n):
            sigma = 0
            for j in range(n):
                if j != i:
                    sigma += A[i, j] * x[j]
            x[i] = (1 - omega) * x[i] + (omega / A[i, i]) * (b[i] - sigma)
        print(f'Iteration {iteration + 1}: x = {x}')
    
    return x

In [53]:
sor_example(S1, b1, 1.3, x0, iterations=2)

Iteration 1: x = [ 0.43333333 -0.28166667  0.65835714  0.          0.        ]
Iteration 2: x = [-0.10401032 -0.13318139  0.67749966  0.          0.        ]


array([-0.10401032, -0.13318139,  0.67749966,  0.        ,  0.        ])

In [54]:
sor_example(S2, b2, 1.3, x0, iterations=2)

Iteration 1: x = [1.17     1.0621   1.056146 0.       0.      ]
Iteration 2: x = [0.957073   0.99038745 0.72065694 0.         0.        ]


array([0.957073  , 0.99038745, 0.72065694, 0.        , 0.        ])

In [55]:
sor_example(S3, b3, 1.3, x0, iterations=2)

Iteration 1: x = [ 0.78      2.743    -0.00455  -2.861183  0.      ]
Iteration 2: x = [-1.23695     3.2287515  -0.15238876 -2.04126618  0.        ]


array([-1.23695   ,  3.2287515 , -0.15238876, -2.04126618,  0.        ])

In [56]:
import numpy as np

def func_relaxation(A, b, omega, x0, iterations=2):
    n = len(b) 
    x = x0.copy()
    
    for iteration in range(iterations):
        for i in range(n):
            sum_before = sum(A[i, j] * x[j] for j in range(i))
            sum_after = sum(A[i, j] * x0[j] for j in range(i + 1, n))
            x[i] = (1 - omega) * x0[i] + (omega / A[i, i]) * (b[i] - sum_before - sum_after)
        x0 = x.copy()
        print(f'Iteration {iteration + 1}: x = {x}')
    
    return x

A = np.array([
    [4, 1, 1, 0, 1],
    [-1, -3, 1, 1, 0],
    [2, 1, 5, -1, -1],
    [-1, -1, -1, 4, 0],
    [0, 2, -1, 1, 4]
], dtype=float)

b = np.array([6, 6, 6, 6, 6], dtype=float)
omega = 1.25 
x0 = np.zeros(5) 
func_relaxation(A, b, omega, x0, iterations=2)



Iteration 1: x = [ 1.875      -3.28125     1.3828125   1.86767578  3.77426147]
Iteration 2: x = [ 0.82005501 -0.66700697  2.32150543  2.18137901  1.39210349]


array([ 0.82005501, -0.66700697,  2.32150543,  2.18137901,  1.39210349])