In [23]:
import numpy as np
import matplotlib.pyplot as plt

In [24]:
# Given Matrices
A1 = np.array([[2, 1], [1, 0]])
A2 = np.array([[2, 1], [1, 0],[0,1]])
A3 = np.array([[2, 1], [-1, 1],[1,1],[2,-1]])
A4 = np.array([[1, 1,0], [-1, 0,1],[0,1,-1],[1,1,-1]])
A5 = np.array([[1, 1,0], [-1, 0,1],[0,1,-1],[1,1,-1]])
A6 = np.array([[0, 1,1], [0, 1,0],[1,1,0],[0,1,0],[1,0,1]])

In [32]:
def func_m(A):
    start_time = time.time()

    #SVD
    U, S, VT = np.linalg.svd(A)

    end_time = time.time()

    time_taken = end_time - start_time
    print(f"Time taken for SVD: {time_taken:.6f} seconds")

    print("U (left singular vector):\n", U)
    print("\nSingular values:\n", S)
    print("\n VT (right singular vector):\n", VT)

    # Reconstructing the original matrix from its SVD
    S_diag = np.zeros((U.shape[1], VT.shape[0]))
    np.fill_diagonal(S_diag, S)
    A_reconstructed = U @ S_diag @ VT

    # the original and reconstructed matrix
    # for demonstrating that the decomposition is correct
    print("\nOriginal matrix A:\n", A)
    print("\nReconstructed matrix from SVD:\n", A_reconstructed)

In [33]:
func_m(A)

Time taken for SVD: 0.001043 seconds
U (left singular vector):
 [[-0.92387953 -0.38268343]
 [-0.38268343  0.92387953]]

Singular values:
 [2.41421356 0.41421356]

 VT (right singular vector):
 [[-0.92387953 -0.38268343]
 [ 0.38268343 -0.92387953]]

Original matrix A:
 [[2 1]
 [1 0]]

Reconstructed matrix from SVD:
 [[ 2.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00 -5.55111512e-17]]


In [34]:
func_m(A2)

Time taken for SVD: 0.000000 seconds
U (left singular vector):
 [[-9.12870929e-01  5.55111512e-17 -4.08248290e-01]
 [-3.65148372e-01 -4.47213595e-01  8.16496581e-01]
 [-1.82574186e-01  8.94427191e-01  4.08248290e-01]]

Singular values:
 [2.44948974 1.        ]

 VT (right singular vector):
 [[-0.89442719 -0.4472136 ]
 [-0.4472136   0.89442719]]

Original matrix A:
 [[2 1]
 [1 0]
 [0 1]]

Reconstructed matrix from SVD:
 [[ 2.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00 -5.55111512e-17]
 [-1.11022302e-16  1.00000000e+00]]


In [35]:
func_m(A3)

Time taken for SVD: 0.000000 seconds
U (left singular vector):
 [[-0.63245553 -0.5        -0.52229321 -0.27786652]
 [ 0.31622777 -0.5        -0.30196857  0.74753928]
 [-0.31622777 -0.5         0.79704714  0.12130893]
 [-0.63245553  0.5        -0.02721464  0.59098169]]

Singular values:
 [3.16227766 2.        ]

 VT (right singular vector):
 [[-1. -0.]
 [-0. -1.]]

Original matrix A:
 [[ 2  1]
 [-1  1]
 [ 1  1]
 [ 2 -1]]

Reconstructed matrix from SVD:
 [[ 2.  1.]
 [-1.  1.]
 [ 1.  1.]
 [ 2. -1.]]


In [36]:
func_m(A4)

Time taken for SVD: 0.001002 seconds
U (left singular vector):
 [[-4.36435780e-01 -4.08248290e-01  7.07106781e-01 -3.77964473e-01]
 [ 4.36435780e-01  4.08248290e-01  7.07106781e-01  3.77964473e-01]
 [-4.36435780e-01  8.16496581e-01 -1.66533454e-16 -3.77964473e-01]
 [-6.54653671e-01 -1.38777878e-17 -8.32667268e-17  7.55928946e-01]]

Singular values:
 [2.64575131 1.         1.        ]

 VT (right singular vector):
 [[-0.57735027 -0.57735027  0.57735027]
 [-0.81649658  0.40824829 -0.40824829]
 [ 0.          0.70710678  0.70710678]]

Original matrix A:
 [[ 1  1  0]
 [-1  0  1]
 [ 0  1 -1]
 [ 1  1 -1]]

Reconstructed matrix from SVD:
 [[ 1.00000000e+00  1.00000000e+00  1.11022302e-16]
 [-1.00000000e+00 -2.77555756e-16  1.00000000e+00]
 [ 1.11022302e-16  1.00000000e+00 -1.00000000e+00]
 [ 1.00000000e+00  1.00000000e+00 -1.00000000e+00]]


In [37]:
func_m(A5)

Time taken for SVD: 0.000000 seconds
U (left singular vector):
 [[-4.36435780e-01 -4.08248290e-01  7.07106781e-01 -3.77964473e-01]
 [ 4.36435780e-01  4.08248290e-01  7.07106781e-01  3.77964473e-01]
 [-4.36435780e-01  8.16496581e-01 -1.66533454e-16 -3.77964473e-01]
 [-6.54653671e-01 -1.38777878e-17 -8.32667268e-17  7.55928946e-01]]

Singular values:
 [2.64575131 1.         1.        ]

 VT (right singular vector):
 [[-0.57735027 -0.57735027  0.57735027]
 [-0.81649658  0.40824829 -0.40824829]
 [ 0.          0.70710678  0.70710678]]

Original matrix A:
 [[ 1  1  0]
 [-1  0  1]
 [ 0  1 -1]
 [ 1  1 -1]]

Reconstructed matrix from SVD:
 [[ 1.00000000e+00  1.00000000e+00  1.11022302e-16]
 [-1.00000000e+00 -2.77555756e-16  1.00000000e+00]
 [ 1.11022302e-16  1.00000000e+00 -1.00000000e+00]
 [ 1.00000000e+00  1.00000000e+00 -1.00000000e+00]]


In [38]:
func_m(A6)

Time taken for SVD: 0.000000 seconds
U (left singular vector):
 [[-5.47722558e-01 -2.77555756e-16 -7.07106781e-01 -1.32058463e-01
  -4.27271064e-01]
 [-3.65148372e-01 -4.08248290e-01  1.52655666e-16 -5.43516408e-01
   6.36073827e-01]
 [-5.47722558e-01  1.38777878e-16  7.07106781e-01 -1.32058463e-01
  -4.27271064e-01]
 [-3.65148372e-01 -4.08248290e-01  1.66533454e-16  8.07633333e-01
   2.18468301e-01]
 [-3.65148372e-01  8.16496581e-01 -2.22044605e-16  1.32058463e-01
   4.27271064e-01]]

Singular values:
 [2.23606798 1.41421356 1.        ]

 VT (right singular vector):
 [[-4.08248290e-01 -8.16496581e-01 -4.08248290e-01]
 [ 5.77350269e-01 -5.77350269e-01  5.77350269e-01]
 [ 7.07106781e-01  3.88578059e-16 -7.07106781e-01]]

Original matrix A:
 [[0 1 1]
 [0 1 0]
 [1 1 0]
 [0 1 0]
 [1 0 1]]

Reconstructed matrix from SVD:
 [[-5.55111512e-17  1.00000000e+00  1.00000000e+00]
 [-3.07844593e-18  1.00000000e+00 -5.24327053e-17]
 [ 1.00000000e+00  1.00000000e+00 -3.33066907e-16]
 [ 6.73463194e-18 

In [ ]:
#Thus we demonstrated that the decomposition is correct