In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [6]:
S1 = np.array([
    [3, -1, 1],
    [3, 6, 2],
    [3, 3, 7]
])
b1 = np.array([1, 0, 4])

x1 = np.linalg.solve(S1, b1)
print(x1)

[ 0.03508772 -0.23684211  0.65789474]


In [9]:
S2 = np.array([
    [10, -1, 0],
    [-1, 10, -2],
    [0, -2, 10]
])
b2 = np.array([9,7,6])

x2 = np.linalg.solve(S2, b2)
print(x2)

[0.99578947 0.95789474 0.79157895]


In [10]:
S3 = np.array([
    [10, 5, 0, 0],
    [5, 10, -4,0],
    [0,-4, 8, -1],
    [0,0,-1,5]
])
b3 = np.array([6, 25, -11,-11])

x3 = np.linalg.solve(S3, b3)
print(x3)

[-0.79764706  2.79529412 -0.25882353 -2.25176471]


In [12]:
S4 = np.array([
    [4, 1, 1, 0,1],
    [-1,-3,1,1,0],
    [2,1,5,-1,-1],
    [-1,-1,-1,4,0],
    [0,2,-1,1,4]
])
b4 = np.array([6,6,6,6,6])

x4 = np.linalg.solve(S4, b4)
print(x4)

[ 0.78663239 -1.00257069  1.86632391  1.9125964   1.98971722]
